import asyncio
import json
import re
import aiohttp
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware
from returnToken import return_token
from typing import Optional
from contextlib import asynccontextmanager

app = FastAPI()

# CORS Configuration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@asynccontextmanager
async def get_aiohttp_session():
    """Async context manager for aiohttp session"""
    session = aiohttp.ClientSession()
    try:
        yield session
    finally:
        await session.close()

async def invoke_chute(prompt: str) -> str:
    """Execute LLM call with proper async resource handling"""
    api_token = return_token()
    headers = {
        "Authorization": f"Bearer {api_token}",
        "Content-Type": "application/json"
    }
    
    body = {
        "model": "deepseek-ai/DeepSeek-V3-0324",
        "messages": [{"role": "user", "content": prompt}],
        "stream": True,
        "max_tokens": 4096,
        "temperature": 0.7
    }

    full_response = []
    async with get_aiohttp_session() as session:
        try:
            async with session.post(
                "https://llm.chutes.ai/v1/chat/completions",
                headers=headers,
                json=body,
                timeout=aiohttp.ClientTimeout(total=30)
            ) as response:
                
                async for line in response.content:
                    if line.startswith(b"data: "):
                        data = line[6:].decode("utf-8").strip()
                        if data == "[DONE]":
                            break
                        try:
                            chunk = json.loads(data)
                            if content := chunk.get("choices", [{}])[0].get("delta", {}).get("content"):
                                full_response.append(content)
                        except json.JSONDecodeError:
                            continue

            clean_response = "".join(full_response)
            return re.sub(r'\n{3,}', '\n\n', clean_response).strip()
            
        except (aiohttp.ClientError, asyncio.TimeoutError) as e:
            raise HTTPException(status_code=500, detail=f"API connection failed: {str(e)}")

class SchemaRequest(BaseModel):
    description: str
    entities: Optional[str] = None
    constraints: Optional[str] = None

# Must be appended to top after AI generates PROMPT_SCHEMA
TOP_SCHEMA_SEGMENT = {
    "$schema": "http://json-schema.org/draft-07/schema#",
  "$meta": {
    "version": "1.0",
    "description": "Universal NoSQL Schema for Generate + Edit Phases"
  }
}

PROMPT_SCHEMA={
  "collections": {
    "AllTypesTest": {
      "name": "AllTypesTest",
      "attributes": {
        "StringField": {
          "type": "string",
          "required": True,
          "validation": { "minLength": 1 }
        },
        "NumberField": {
          "type": "number",
          "required": False,
          "validation": { "min": 0 }
        },
        "BooleanField": {
          "type": "boolean",
          "required": False
        },
        "DateField": {
          "type": "date",
          "required": False
        },
        "EnumField": {
          "type": "enum",
          "subtype": "enum",
          "values": ["a", "b", "c"]
        },
        "NullField": {
          "type": "null"
        },
        "ArrayField": {
          "type": "array",
          "structure": "embedded",
          "items": {
            "type": "string"
          }
        },
        "ObjectField": {
          "type": "object",
          "structure": "embedded",
          "properties": {
            "NestedKey": {
              "type": "boolean"
            }
          }
        }
      }
    }
  }
}

# Must be appended to bottom after AI generates PROMPT_SCHEMA
BOTTOM_SCHEMA_SEGMENT = {
    "exportOptions": {
    "mongodb": {
      "indexes": [
        { 
          "collection": "Orders", 
          "fields": { "Status": 1 }, 
          "options": { "unique": False } 
        }
      ]
    },
    "cassandra": {
      "compaction": { "class": "SizeTieredCompactionStrategy" },
      "clusteringOrder": { "Orders": { "OrderTime": "DESC" } }
    },
    "firebase": {
      "collectionGroups": ["Orders"]
    }
  }
}


# TODO: Only Actual Entities will be generated by AI. Therefore, options, indexes, and keys as well as the $schema, $meta will be added outside of the LLM Call.
# TODO: The LLM will only generate the attributes of the schema. The rest will be added by the backend.
# For now, we are returning the example schema directly for UI testing purposes.

@app.post("/generate-schema")
async def generate(data: SchemaRequest):
    if not data.description:
        raise HTTPException(status_code=400, detail="Description is mandatory.")

    prompt = (
        f"Generate NoSQL JSON schema collections section exactly matching this structure:\n"
        f"{json.dumps(PROMPT_SCHEMA['collections'], indent=2)}\n\n"
        f"Requirements:\n"
        f"- Description: {data.description}\n"
        f"- Entities: {data.entities or 'none'}\n"
        f"- Constraints: {data.constraints or 'none'}\n\n"
        "Rules:\n"
        "1. Maintain exact type definitions and nesting structure as shown in the example\n"
        "2. Output ONLY the collections section in pure JSON format (starting with '{' and ending with '}')\n"
        "3. Include only valid attributes based on the data types shown in the example\n"
        "4. Do not include any additional metadata or schema information\n"
        "5. Ensure all required fields are marked and validation rules are properly set"
    )

    try:
        raw_json = await invoke_chute(prompt)
        try:
            # Extract the JSON portion from the response
            json_start = raw_json.find('{')
            json_end = raw_json.rfind('}') + 1
            collections_section = json.loads(raw_json[json_start:json_end])
            
            # Build the complete schema by combining all parts
            complete_schema = {
                **TOP_SCHEMA_SEGMENT,
                "collections": collections_section,
                **BOTTOM_SCHEMA_SEGMENT
            }
            
            # For now, just print the result (as per your request)
            print("Generated Schema Structure:")
            print(json.dumps(complete_schema, indent=2))
            
            return {"schema": complete_schema}
            
        except json.JSONDecodeError as e:
            raise HTTPException(status_code=422, detail=f"Invalid JSON response from AI: {str(e)}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Schema generation failed: {str(e)}")

@app.get("/")
async def read_root():
    return {"message": "Welcome to the FastAPI application!"}



